#!/usr/bin/env bash
# init.sh — CMake project health check.
# Generated by harness-anchor /cpp-init for CMake projects.
set -euo pipefail

echo "=== harness-anchor: CMake project init ==="
echo "Repo: $(pwd)"
echo "Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

FAIL=0

# ---- harness state files ----
echo "[1/4] Verifying harness state files..."
for f in AGENTS.md feature_list.json progress.md session-handoff.md PROJECT-TOC.md; do
    if [ ! -f "$f" ]; then echo "  MISSING: $f"; FAIL=1; else echo "  OK:      $f"; fi
done
echo ""

# ---- toolchain ----
echo "[2/4] Verifying toolchain..."
for tool in git cmake; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  OK:      $tool ($(command -v "$tool"))"
    else
        echo "  MISSING: $tool"
        FAIL=1
    fi
done
# Optional but recommended
for tool in clang-tidy clang-format; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  OK:      $tool (optional)"
    else
        echo "  WARN:    $tool not installed (optional but recommended)"
    fi
done
echo ""

# ---- configure ----
echo "[3/4] CMake configure (out-of-source: .build/)..."
if cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G "Unix Makefiles" >/dev/null 2>.build-configure.log; then
    echo "  OK:      configure succeeded"
    # Symlink compile_commands.json to root for tooling
    [ -f .build/compile_commands.json ] && ln -sf .build/compile_commands.json compile_commands.json
else
    echo "  FAIL:    configure failed — see .build-configure.log"
    FAIL=1
fi
echo ""

# ---- build (light check; skip on large projects) ----
echo "[4/4] CMake build..."
if cmake --build .build -j >.build-build.log 2>&1; then
    echo "  OK:      build succeeded"
else
    echo "  FAIL:    build failed — see .build-build.log"
    FAIL=1
fi
echo ""

if [ "$FAIL" -eq 0 ]; then
    echo "=== init.sh OK ==="
    exit 0
else
    echo "=== init.sh FAILED — fix above before starting work ==="
    exit 1
fi
