#!/usr/bin/env bash
# lint.sh — clang-tidy wrapper with the platform sysroot handled.
# Generated by harness-anchor /cpp-init.
#
# Why this wrapper exists:
#   compile_commands.json produced with Apple clang implies the macOS SDK; Homebrew
#   clang-tidy does NOT know it, so a bare run fails with "'<header>' file not found"
#   and emits garbage diagnostics from the half-parsed TU (see the cpp-static-analysis
#   skill). This wrapper injects the SDK sysroot when `xcrun` is available; elsewhere
#   it is a plain clang-tidy passthrough.
#
# Usage:
#   bash scripts/lint.sh                    # lint all tracked C/C++ sources
#   bash scripts/lint.sh src/foo.cpp ...    # lint specific files (preferred mid-feature:
#                                           # changed files only — scope discipline)
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

FILES=("$@")
if [ ${#FILES[@]} -eq 0 ]; then
    # Adjust per project if you want a narrower default (e.g. src/*.cpp).
    while IFS= read -r f; do FILES+=("$f"); done < <(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx')
fi
if [ ${#FILES[@]} -eq 0 ]; then
    echo "lint.sh: no C/C++ sources found (git ls-files)"
    exit 0
fi

EXTRA=()
# macOS: point clang-tidy at the active SDK so it can find Apple's libc++ headers.
if command -v xcrun >/dev/null 2>&1; then
    EXTRA=(--extra-arg=-isysroot "--extra-arg=$(xcrun --show-sdk-path)")
fi

exec clang-tidy -p . ${EXTRA[@]+"${EXTRA[@]}"} "${FILES[@]}"
