#!/usr/bin/env bash
# init.sh — Meson project health check.
# Generated by harness-anchor /cpp-init for Meson projects.
set -euo pipefail

echo "=== harness-anchor: Meson project init ==="
FAIL=0

echo "[1/4] Verifying harness state files..."
for f in AGENTS.md feature_list.json progress.md session-handoff.md PROJECT-TOC.md; do
    if [ ! -f "$f" ]; then echo "  MISSING: $f"; FAIL=1; else echo "  OK:      $f"; fi
done
echo ""

echo "[2/4] Verifying toolchain..."
for tool in git meson ninja; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  OK:      $tool"
    else
        echo "  MISSING: $tool"
        FAIL=1
    fi
done
for tool in clang-tidy clang-format; do
    if command -v "$tool" >/dev/null 2>&1; then
        echo "  OK:      $tool (optional)"
    else
        echo "  WARN:    $tool not installed (optional)"
    fi
done
echo ""

echo "[3/4] Meson setup..."
if meson setup builddir >builddir-setup.log 2>&1; then
    echo "  OK:      setup succeeded"
    [ -f builddir/compile_commands.json ] && ln -sf builddir/compile_commands.json compile_commands.json
else
    echo "  FAIL:    meson setup failed — see builddir-setup.log"
    FAIL=1
fi
echo ""

echo "[4/4] Meson compile..."
if meson compile -C builddir >builddir-compile.log 2>&1; then
    echo "  OK:      compile succeeded"
else
    echo "  FAIL:    compile failed — see builddir-compile.log"
    FAIL=1
fi
echo ""

if [ "$FAIL" -eq 0 ]; then
    echo "=== init.sh OK ==="
    exit 0
else
    echo "=== init.sh FAILED ==="
    exit 1
fi
