#!/usr/bin/env bash
# sanitizer-build.sh — Build with ASan + UBSan and run tests.
# Generated by harness-anchor /cpp-init. CMake assumed; adapt for Meson.
set -euo pipefail

BUILD_DIR=".build/asan"

echo "=== harness-anchor: sanitizer build (ASan + UBSan) ==="

# ASAN_OPTIONS: detect_leaks=1 — on by default on Linux; on macOS supported but off by
# default, so we set it explicitly here (no-op on platforms without LeakSanitizer).
export ASAN_OPTIONS="${ASAN_OPTIONS:-abort_on_error=1:halt_on_error=1:detect_leaks=1:check_initialization_order=1}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-print_stacktrace=1:halt_on_error=1}"

cmake -S . -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all -g -O1" \
    -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all -g -O1" \
    -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" -j

echo ""
echo "=== Running tests under ASan+UBSan ==="
ctest --test-dir "$BUILD_DIR" --output-on-failure
