#!/usr/bin/env bash
# sanitizer-build.sh — Build with ASan + UBSan and run tests.
# Generated by harness-anchor /cpp-init. CMake assumed; adapt for Meson.
# If this SCRIPT itself fails (not your tests), that's sanitizer infra, not a code
# finding — see the cpp-sanitizers skill (platform notes) or docs-lookup.
set -euo pipefail

BUILD_DIR=".build/asan"

echo "=== harness-anchor: sanitizer build (ASan + UBSan) ==="

# LeakSanitizer is unavailable on macOS/Apple toolchains AND on Windows — forcing
# detect_leaks=1 there makes ASan abort at startup ("detect_leaks is not supported
# on this platform"). Pick per-OS: leak detection on Linux, off elsewhere.
# Leak hunting elsewhere: macOS → leaks(1)/Instruments; Windows → CRT debug heap
# (_CrtDumpMemoryLeaks) or Dr. Memory; or run the LSan suite on Linux CI.
case "$(uname -s)" in
    Darwin|MINGW*|MSYS*|CYGWIN*) DETECT_LEAKS=0 ;;
    *)                           DETECT_LEAKS=1 ;;
esac
export ASAN_OPTIONS="${ASAN_OPTIONS:-abort_on_error=1:halt_on_error=1:detect_leaks=${DETECT_LEAKS}:check_initialization_order=1}"
export UBSAN_OPTIONS="${UBSAN_OPTIONS:-print_stacktrace=1:halt_on_error=1}"

cmake -S . -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all -g -O1" \
    -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-sanitize-recover=all -g -O1" \
    -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" -j

echo ""
echo "=== Running tests under ASan+UBSan ==="
ctest --test-dir "$BUILD_DIR" --output-on-failure
