#!/usr/bin/env bash
# lint.sh — clang-tidy wrapper with the compile DB located and the platform sysroot handled.
# Generated by harness-anchor /cpp-init.
#
# Why this wrapper exists:
#   compile_commands.json produced with Apple clang implies the macOS SDK; Homebrew
#   clang-tidy does NOT know it, so a bare run fails with "'<header>' file not found"
#   and emits garbage diagnostics from the half-parsed TU (see the cpp-static-analysis
#   skill). This wrapper locates the compilation database and injects the SDK sysroot
#   when available; elsewhere it is a plain clang-tidy passthrough.
#
# Usage:
#   bash scripts/lint.sh                    # lint all tracked C/C++ sources
#   bash scripts/lint.sh src/foo.cpp ...    # lint specific files (preferred mid-feature:
#                                           # changed files only — scope discipline)
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

# Locate the compilation database (same search order as the PostToolUse hook).
CC_DIR=""
for d in . .build build builddir; do
    if [ -f "$d/compile_commands.json" ]; then
        CC_DIR="$d"
        break
    fi
done
if [ -z "$CC_DIR" ]; then
    echo "lint.sh: compile_commands.json not found (looked in ., .build/, build/, builddir/)." >&2
    echo "Generate it, e.g.: cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  (or run: bash init.sh)" >&2
    exit 1
fi

FILES=("$@")
if [ ${#FILES[@]} -eq 0 ]; then
    # Adjust per project if you want a narrower default (e.g. src/*.cpp).
    while IFS= read -r f; do FILES+=("$f"); done < <(git ls-files '*.c' '*.cc' '*.cpp' '*.cxx')
fi
if [ ${#FILES[@]} -eq 0 ]; then
    echo "lint.sh: no C/C++ sources found (git ls-files)"
    exit 0
fi

EXTRA=()
# macOS: point clang-tidy at the active SDK so it can find Apple's libc++ headers.
# Soft fallback: if xcrun fails or reports nothing, run without sysroot args.
if [ "$(uname -s)" = "Darwin" ] && command -v xcrun >/dev/null 2>&1; then
    SDK_PATH=$(xcrun --show-sdk-path 2>/dev/null || true)
    if [ -n "$SDK_PATH" ]; then
        EXTRA=(--extra-arg=-isysroot "--extra-arg=$SDK_PATH")
    else
        echo "lint.sh: xcrun could not report an SDK path — running clang-tidy without -isysroot" >&2
    fi
fi

exec clang-tidy -p "$CC_DIR" ${EXTRA[@]+"${EXTRA[@]}"} "${FILES[@]}"
