# AGENTS.md — Operating Manual for AI Coding Agents

> Generated by harness-anchor `/anchor`. Edit freely to match your project.
> Symlinked alias: `CLAUDE.md` → same file. Keep this a **map, not a manual** (≤ ~80 lines) —
> deep detail belongs in the files it points to.

## Commands

<!-- TODO: fill in the real commands for THIS project. Commands come first — agents reach for these constantly. -->

```bash
# Build:
# Test:
# Lint:
# Type-check:
# Run:
```

## Startup Rules

Before writing or modifying any code, complete these in order:

1. **Read this file completely.**
2. **Read `feature_list.json`** — identify the single active feature (`status: "in-progress"`). Work only on that.
3. **Read `PROJECT-TOC.md`** — navigate by index, not by `Glob`. Start with its **`## Directory map`**, then drill into the **`## Files`** entries beneath it.
4. **Read `golden-rules.md`** — the project's accumulated taste / anti-pattern rules. Honor them.
5. **Read `session-handoff.md`** — pick up from where the previous session left off.
6. **Run `bash init.sh`** — verify the environment is healthy before doing anything else. Fix any reported issues first.

## Project Context

<!-- TODO: 1-3 sentences — what this project is, who uses it, the tech stack (be precise: language + version). -->

## Conventions

<!-- TODO: code style, naming, file layout. Prefer a short example over prose: -->

```
# Good:   <a one-line example of the idiom you want>
# Avoid:  <the anti-idiom>
```

Project-specific taste rules accrue in **`golden-rules.md`** (added when a mistake recurs — see the `capturing-golden-rules` skill). Read it alongside this section.

## Git workflow

<!-- TODO: adapt to your project. These defaults are intentionally neutral — replace with your own conventions. -->

- Small, focused commits — one logical change each.
- **Do not commit or push unless asked.** When you do, branch off the default branch first if needed.
- Branch-naming / commit-message convention: <TODO — e.g. a prefix scheme, only if your team uses one>.

## Definition of Done

A feature is "done" — i.e. its `status` may be flipped to `"pass"` in `feature_list.json` — only when:

1. Build/compile passes — capture the build log path as evidence.
2. Type-check passes (where applicable) — capture command output.
3. Test suite passes — capture test runner output (N passed, 0 failed).
4. Static analysis warnings reviewed (lint / clang-tidy / equivalent).
5. `feature_list.json` updated with ISO timestamp + commit SHA in the `evidence` field.

**Default-FAIL contract**: each criterion starts `false`. You may not assert "done" without an evidence path. If uncertain, say so explicitly: *"I am uncertain whether X passes because <reason>. Recommend running <command> to verify."*

## Scope Boundaries

- One active feature at a time. If you discover new work, add it to `feature_list.json` with `status: "planned"` (do NOT begin it). Give it a **unique `id`** — verify with `node ${CLAUDE_PLUGIN_ROOT}/scripts/feature-list-validate.mjs --check <id>` before writing, rather than eyeballing the list.
- If the user adds an unrelated request mid-feature, surface the scope-jump and ask for explicit confirmation before pivoting.

## Session Handoff

When **resuming** work: read `session-handoff.md` first.

When **finishing** a session: run `/session-end` — it writes the handoff (what was accomplished, what remains, blockers, the ONE next action) and prompts you to capture any recurring lesson as a golden rule.
