# AGENTS.md — Operating Manual for AI Coding Agents

> Generated by harness-anchor `/anchor`. Edit freely to match your project.
> Symlinked alias: `CLAUDE.md` → same file.

## Startup Rules

Before writing or modifying any code, complete these steps in order:

1. **Read this file completely.**
2. **Read `feature_list.json`** — identify the single active feature (`status: "in-progress"`). Work only on that.
3. **Read `PROJECT-TOC.md`** — navigate by index, not by `Glob` everywhere.
4. **Read `session-handoff.md`** — pick up from where the previous session left off.
5. **Run `bash init.sh`** — verify environment is healthy before doing anything else. Fix any reported issues first.

## Project Context

<!-- TODO: 1-3 sentences describing what this project is, who uses it, what tech stack -->

## Conventions

<!-- TODO: language version, code style, naming rules, file layout -->

## Definition of Done

A feature is "done" — i.e. its `status` may be flipped to `"pass"` in `feature_list.json` — only when:

1. Build/compile passes — capture the build log path as evidence.
2. Type-check passes (where applicable) — capture command output.
3. Test suite passes — capture test runner output (N passed, 0 failed).
4. Static analysis warnings reviewed (lint / clang-tidy / equivalent).
5. `feature_list.json` updated with ISO timestamp + commit SHA in the `evidence` field.

**Default-FAIL contract**: each criterion starts `false`. You may not assert "done" without an evidence path. If uncertain, say so explicitly: *"I am uncertain whether X passes because <reason>. Recommend running <command> to verify."*

## Session Handoff

When **resuming** work: read `session-handoff.md` first.

When **finishing** a session: update `session-handoff.md` with:

- What was accomplished (concrete: files changed, tests added, decisions made)
- What remains for the active feature
- Any blockers or open questions
- Recommended next session's first action

Run `/session-end` for guided handoff.

## Scope Boundaries

- One active feature at a time. If you discover new work, add it to `feature_list.json` with `status: "planned"` — do NOT begin it.
- If the user adds an unrelated request mid-feature, surface the scope-jump and ask for explicit confirmation before pivoting.

## Verification Commands

<!-- TODO: fill in for this project -->

```bash
# Build
# Test
# Lint
# Type-check
```
