# Context Budget

> Track per-session context allocation per harness-anchor's SELECT/WRITE/COMPRESS/ISOLATE discipline.
> Generated by harness-anchor `/anchor`. Update during long sessions if context pressure rises.

## Tier 1 — Always loaded (~2000 token budget)

| Block | Source | Approx tokens | Notes |
|---|---|---|---|
| `using-superpowers` | superpowers SessionStart | ~1500 | If superpowers installed |
| `using-harness-anchor` | this plugin SessionStart | ~700 | Includes `<harness-anchor>` banner |
| Active feature | `feature_list.json` extract | ~50 | id + name + status |
| PROJECT-TOC head | `PROJECT-TOC.md` first N lines | ~500 | Dynamic, fits remaining budget |
| Session handoff head | `session-handoff.md` first 10 lines | ~150 | |

## Tier 2 — On-demand (skill activation)

Loaded when agent invokes Skill tool. Each skill SKILL.md ≤ 3000 tokens.

## Tier 3 — Reference

Sibling `.md` files in skill directories. Loaded only when explicitly read.

## Compaction Triggers

- Context usage > 80% of model window → trigger context reset (not just compaction) per Anthropic Nov 2025 guidance.
- Use `/session-end` to write rich handoff before reset.

## Project-specific TODO

<!-- Edit to record this project's context pressure points -->
