# Context Budget

> Track per-session context allocation per harness-anchor's SELECT/WRITE/COMPRESS/ISOLATE discipline.
> Generated by harness-anchor `/anchor`. Update during long sessions if context pressure rises.

## Tier 1 — Always loaded

| Block | Source | Approx tokens | Notes |
|---|---|---|---|
| `using-superpowers` | superpowers SessionStart | ~1500 | If superpowers is installed — its own budget, separate from harness-anchor's cap |
| harness-anchor injection (= the three parts below) | this plugin's SessionStart | **generic ≈1160 / C-C++ ≈1580 measured / 3000 cap** | Hard-capped at 12000 chars; re-measure the plugin baselines anytime: `bash ${CLAUDE_PLUGIN_ROOT}/scripts/measure-context.sh` |
| ├ state banner | `<harness-anchor-state>` block | ~150 | active feature, project type, TOC freshness, golden-rules count, state-budget sentinel, handoff head (first 10 lines) |
| ├ TOC view | `<project-toc>` adaptive block | leftover-sized (~1700 available on a generic project) | full `## Files` when it fits; directory map (or just its top levels) on large repos |
| └ meta-skill body | `using-harness-anchor` SKILL.md | ~1050 generic / ~1200 C-C++ | injected slimmed (no frontmatter; cpp-only regions gated by cpp-detect); truncated last if the cap would be exceeded |

Measured at v0.10.0 on the reference fixtures; the TOC and handoff parts vary per project.
Tier-1 headroom is deliberate — it belongs to the TOC block, not to new always-on content.

## Tier 2 — On-demand (skill activation)

Loaded when agent invokes Skill tool. Each skill SKILL.md stays ≤ ~3000 tokens (review-enforced; the largest shipped skill measures ≈ 2800 at v0.9.0).

## Tier 3 — Reference

Sibling `.md` files in skill directories. Loaded only when explicitly read.

## Compaction Triggers

- Context usage > 80% of model window → trigger context reset (not just compaction) per Anthropic Nov 2025 guidance.
- Use `/session-end` to write rich handoff before reset.

## Project-specific TODO

<!-- Edit to record this project's context pressure points -->
