# Golden Rules — PROJECT_NAME_PLACEHOLDER

> Generated by harness-anchor `/anchor`. Project-specific **golden rules** — the taste /
> consistency rules this project enforces, each tied to a concrete past mistake.
> `/gc` (the `drift-analyst`) scans changed code against these; the `capturing-golden-rules`
> skill adds to them. Kept separate from AGENTS.md on purpose: rules grow, the map shouldn't.

<!-- HOW TO USE
Add a rule when the SAME mistake or bad pattern recurs (the second occurrence is the
trigger), or when a review comment is really a convention worth enforcing from now on.

This file is the home for FAILURE -> guardrail signals only. Route other learning elsewhere:
  - a fact/version/convention the AI keeps missing  -> AGENTS.md (Conventions / Project Context)
  - a prompt phrasing that reliably works           -> a skill, or AGENTS.md
  - a workflow that reliably produces good work      -> AGENTS.md / session-handoff.md

Each rule should tie to a real failure and be checkable. The Check can start as
"manual review" and graduate to a grep/lint command only when the rule is violated often
enough to be worth automating — not every rule needs a tool. Prune rules that no longer
apply: entropy applies to this file too.
-->

## Rules

<!-- Example shape (delete and replace with real rules):

### GR-1 — Use the shared logger; never bare stdout/print in library code
- **Why / origin:** a change shipped stray debug prints that leaked into program output.
- **Check:** `grep -rn "console.log\|printf(\|println!" src/` returns nothing unexpected.

-->

_No rules yet — add your first when a pattern recurs (see the `capturing-golden-rules` skill)._
