#!/usr/bin/env bash
# init.sh — Verify the project environment is healthy before agent work begins.
# Generated by harness-anchor `/anchor`. Customize the COMMANDS section below.
#
# Exit code 0 = healthy, non-zero = something needs fixing (do not start work).
set -euo pipefail

echo "=== harness-anchor: init ==="
echo "Repo: $(pwd)"
echo "Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

FAIL=0

check_file() {
    if [ ! -f "$1" ]; then
        echo "  MISSING: $1"
        FAIL=1
    else
        echo "  OK:      $1"
    fi
}

echo "[1/3] Verifying harness state files..."
check_file AGENTS.md
check_file feature_list.json
check_file progress.md
check_file session-handoff.md
check_file PROJECT-TOC.md
echo ""

echo "[2/3] Verifying tools..."
# shellcheck disable=SC2043  # seeded with git only by design — append your project's tools here
for tool in git; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "  MISSING tool: $tool"
        FAIL=1
    else
        echo "  OK:           $tool ($(command -v "$tool"))"
    fi
done
echo ""

# === COMMANDS — replace with your project's actual build/test/lint commands ===
# Examples (uncomment what applies):
#
#   echo "[3/3] Installing dependencies..."
#   npm install || FAIL=1
#
#   echo "[3/3] CMake configure..."
#   cmake -S . -B .build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON || FAIL=1
#
#   echo "[3/3] Type check..."
#   npm run typecheck || FAIL=1
#
echo "[3/3] Project-specific health check..."
echo "  (no project commands configured; edit init.sh to add them)"
echo ""

if [ "$FAIL" -eq 0 ]; then
    echo "=== init.sh OK ==="
    exit 0
else
    echo "=== init.sh FAILED — fix the above before starting work ==="
    exit 1
fi
