# Progress Log

> Append-only history of agent sessions. Most-recent first.
> Generated by harness-anchor `/anchor`. Agents should append a new section at every `/session-end`.

---

## YYYY-MM-DD HH:MM — Session N

**Active feature**: <feature-id>
**Status when session started**: <planned | in-progress>
**Status when session ended**: <in-progress | pass | blocked>

### Accomplished
-

### Files changed
-

### Evidence collected
-

### Remaining for active feature
-

### Decisions made (link to ADR if applicable)
-

### Next session's first action
-

---
